### ISSUE TITLE
More Frequencys

### ISSUE THREAD

**Issue by zcbml88** [SHUR1K-N/Flipper-Zero-Sub-GHz-Jamming-Files#15]
Can you make a jamming file for 851.80mhz please?

**Comment by skyblur12** [comment]
Sure thing  i will email it to ya not post it and this is usa sub-GHZ
correct

**Comment by zcbml88** [comment]
USA

**Comment by zcbml88** [comment]
Can you email me the jammer file for 851.85mhz please

**Comment by zcbml88** [comment]
Can you email me the jammer file for 851.85mhz please
