### ISSUE TITLE
accord hond vehicle is 313.8 Mhz 

### ISSUE THREAD

**Issue by rotivrotiv** [SHUR1K-N/Flipper-Zero-Sub-GHz-Jamming-Files#5]
I inform you that the frequency of the accord hond vehicle is 313.8 Mhz - can you expand one more .SUB on this frequency?

Another question: is there any way to run ALL frequencies at once? I say this because we will not always know the exact frequency of the target in question!

**Comment by SHUR1K-N** [comment]
I don't have that frequency yet. If or when I do, I'll add it to the repo.

Multiple frequencies cannot be transmitted from the Zero simultaneously. Careful with this stuff, don't get arrested. :)
